import "./globals.css";
import type { Metadata } from "next";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Next.js13 MyBlog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body className="container mx-auto bg-indigo-400 text-slate-50">
        <Header/>
        {children}
        <footer>footer</footer>
      </body>
    </html>
  );
}
